# Toy dataset 1

In [1]:
import torch as th

In [2]:
input_tensor = th.tensor([[1,1],[1.0,0],[1,1],[0,0],[0,1],[0,0]],requires_grad=True)
target_tensor = th.tensor([[1.0],[1],[1],[0],[0],[0]],requires_grad=True)

In [3]:
from torch.optim import optimizer
from torch import optim
from torch import nn
import torch.nn.functional as F
# class Classifier(nn.Module):
#     def __init__(self):
#         super().__init__()
#         self.fc = nn.Linear(2,1)
#     def forward(self,x):
#         x = F.ReLU(self.fc(x))
#         return x
model = nn.Linear(2,1)

In [4]:
input_tensor.shape

torch.Size([6, 2])

In [5]:
target_tensor.shape

torch.Size([6, 1])

In [6]:
target_tensor

tensor([[1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.]], requires_grad=True)

In [7]:
# target_tensor.squeeze()

In [8]:
# criterion = nn.BCEWithLogitsLoss()

optimizer = optim.SGD(model.parameters(), lr =0.1)

for i in range(50):
    optimizer.zero_grad()
    predict_tensor = model(input_tensor)
    # print(predict_tensor)
#     loss = criterion(predict_tensor,target_tensor)
    loss = ((predict_tensor - target_tensor)**2).sum()
    loss.backward()
    optimizer.step()
    print(loss.data)

tensor(0.8395)
tensor(0.5639)
tensor(0.3985)
tensor(0.2968)
tensor(0.2324)
tensor(0.1898)
tensor(0.1603)
tensor(0.1387)
tensor(0.1222)
tensor(0.1088)
tensor(0.0977)
tensor(0.0882)
tensor(0.0799)
tensor(0.0725)
tensor(0.0659)
tensor(0.0599)
tensor(0.0545)
tensor(0.0496)
tensor(0.0452)
tensor(0.0411)
tensor(0.0375)
tensor(0.0341)
tensor(0.0311)
tensor(0.0283)
tensor(0.0258)
tensor(0.0235)
tensor(0.0214)
tensor(0.0195)
tensor(0.0177)
tensor(0.0162)
tensor(0.0147)
tensor(0.0134)
tensor(0.0122)
tensor(0.0111)
tensor(0.0101)
tensor(0.0092)
tensor(0.0084)
tensor(0.0077)
tensor(0.0070)
tensor(0.0064)
tensor(0.0058)
tensor(0.0053)
tensor(0.0048)
tensor(0.0044)
tensor(0.0040)
tensor(0.0036)
tensor(0.0033)
tensor(0.0030)
tensor(0.0027)
tensor(0.0025)


In [9]:
predict = model(th.tensor([1.0,1.0]))

In [10]:
predict

tensor([1.0257], grad_fn=<AddBackward0>)

# Toy Dataset 2

In [11]:
input_tensor = th.tensor([[5.8],[6.0],[5.5],[4.5],[4.1],[3.5]],requires_grad=True)
target_tensor = th.tensor([[1.0],[1],[1],[0],[0],[0]],requires_grad=False)

In [12]:
from torch.optim import optimizer
from torch import optim
from torch import nn
import torch.nn.functional as F
model = nn.Linear(1,1)

In [14]:
criterion = nn.BCEWithLogitsLoss()

optimizer = optim.SGD(model.parameters(), lr =0.4,momentum=0.8)

for i in range(10000):
    optimizer.zero_grad()
    predict_tensor = model(input_tensor)
    loss = criterion(predict_tensor,target_tensor)
    loss.backward()
    optimizer.step()
    print(loss.data)

tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0044)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0043)
tensor(0.0

tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0041)
tensor(0.0

tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0039)
tensor(0.0

tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0037)
tensor(0.0

tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0036)
tensor(0.0

tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0034)
tensor(0.0

tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0033)
tensor(0.0

tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0032)
tensor(0.0

tensor(0.0031)
tensor(0.0031)
tensor(0.0031)
tensor(0.0031)
tensor(0.0031)
tensor(0.0031)
tensor(0.0031)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0030)
tensor(0.0

tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0029)
tensor(0.0

tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0028)
tensor(0.0

tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0

tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0027)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0

tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0026)
tensor(0.0

tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0025)
tensor(0.0

tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0

tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0024)
tensor(0.0

In [15]:
model(th.tensor([4.5]))

tensor([-4.8872], grad_fn=<AddBackward0>)

In [16]:
print(predict_tensor)

tensor([[  8.1261],
        [ 10.1282],
        [  5.1231],
        [ -4.8871],
        [ -8.8912],
        [-14.8974]], grad_fn=<AddmmBackward>)


In [17]:
model(th.tensor([5.5]))

tensor([5.1231], grad_fn=<AddBackward0>)

In [18]:
model(th.tensor([4.5]))

tensor([-4.8872], grad_fn=<AddBackward0>)

In [30]:
model(th.tensor([-1.0]))

tensor([-59.9439], grad_fn=<AddBackward0>)

In [21]:
print(model.weight.data)

tensor([[10.0103]])


In [22]:
print(model.bias.data)

tensor([-49.9336])


In [31]:
x = -1

In [32]:
(10.0103*x)- 49.9336

-59.9439