# Toy dataset 1

In [1]:
import torch as th

In [2]:
input_tensor = th.tensor([[1,1],[1.0,0],[1,1],[0,0],[0,1],[0,0]],requires_grad=True)
target_tensor = th.tensor([[1.0],[1],[1],[0],[0],[0]],requires_grad=True)

In [3]:
from torch.optim import optimizer
from torch import optim
from torch import nn
import torch.nn.functional as F
# class Classifier(nn.Module):
#     def __init__(self):
#         super().__init__()
#         self.fc = nn.Linear(2,1)
#     def forward(self,x):
#         x = F.ReLU(self.fc(x))
#         return x
model = nn.Linear(2,1)

In [4]:
input_tensor.shape

torch.Size([6, 2])

In [5]:
target_tensor.shape

torch.Size([6, 1])

In [6]:
target_tensor

tensor([[1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.]], requires_grad=True)

In [7]:
# target_tensor.squeeze()

In [8]:
# criterion = nn.BCEWithLogitsLoss()

optimizer = optim.SGD(model.parameters(), lr =0.1)

for i in range(50):
    optimizer.zero_grad()
    predict_tensor = model(input_tensor)
    # print(predict_tensor)
#     loss = criterion(predict_tensor,target_tensor)
    loss = ((predict_tensor - target_tensor)**2).sum()
    loss.backward()
    optimizer.step()
    print(loss.data)

tensor(0.9000)
tensor(0.6076)
tensor(0.4236)
tensor(0.3062)
tensor(0.2299)
tensor(0.1792)
tensor(0.1445)
tensor(0.1200)
tensor(0.1020)
tensor(0.0884)
tensor(0.0777)
tensor(0.0690)
tensor(0.0618)
tensor(0.0556)
tensor(0.0502)
tensor(0.0454)
tensor(0.0412)
tensor(0.0374)
tensor(0.0340)
tensor(0.0309)
tensor(0.0281)
tensor(0.0256)
tensor(0.0233)
tensor(0.0212)
tensor(0.0193)
tensor(0.0176)
tensor(0.0160)
tensor(0.0146)
tensor(0.0133)
tensor(0.0121)
tensor(0.0110)
tensor(0.0101)
tensor(0.0092)
tensor(0.0083)
tensor(0.0076)
tensor(0.0069)
tensor(0.0063)
tensor(0.0057)
tensor(0.0052)
tensor(0.0048)
tensor(0.0043)
tensor(0.0040)
tensor(0.0036)
tensor(0.0033)
tensor(0.0030)
tensor(0.0027)
tensor(0.0025)
tensor(0.0023)
tensor(0.0021)
tensor(0.0019)


In [9]:
predict = model(th.tensor([1.0,1.0]))

In [10]:
predict

tensor([0.9777], grad_fn=<AddBackward0>)

# Toy Dataset 2

In [11]:
input_tensor = th.tensor([[5.8],[6.0],[5.5],[4.5],[4.1],[3.5]],requires_grad=True)
target_tensor = th.tensor([[1.0],[1],[1],[0],[0],[0]],requires_grad=False)

In [12]:
from torch.optim import optimizer
from torch import optim
from torch import nn
import torch.nn.functional as F
model = nn.Linear(1,1)

In [13]:
criterion = nn.BCEWithLogitsLoss()

optimizer = optim.SGD(model.parameters(), lr =0.4,momentum=0.8)

for i in range(10000):
    optimizer.zero_grad()
    predict_tensor = model(input_tensor)
    loss = criterion(predict_tensor,target_tensor)
    loss.backward()
    optimizer.step()
    print(loss.data)

tensor(1.9452)
tensor(1.0734)
tensor(1.4687)
tensor(0.7035)
tensor(1.3990)
tensor(0.6893)
tensor(1.0162)
tensor(0.6613)
tensor(0.9279)
tensor(0.7159)
tensor(0.7161)
tensor(0.7304)
tensor(0.6027)
tensor(0.6614)
tensor(0.5878)
tensor(0.5940)
tensor(0.5898)
tensor(0.5492)
tensor(0.5673)
tensor(0.5336)
tensor(0.5260)
tensor(0.5206)
tensor(0.4988)
tensor(0.4981)
tensor(0.4828)
tensor(0.4759)
tensor(0.4685)
tensor(0.4576)
tensor(0.4528)
tensor(0.4428)
tensor(0.4369)
tensor(0.4294)
tensor(0.4224)
tensor(0.4165)
tensor(0.4095)
tensor(0.4040)
tensor(0.3976)
tensor(0.3922)
tensor(0.3865)
tensor(0.3811)
tensor(0.3759)
tensor(0.3708)
tensor(0.3659)
tensor(0.3610)
tensor(0.3565)
tensor(0.3519)
tensor(0.3475)
tensor(0.3431)
tensor(0.3390)
tensor(0.3349)
tensor(0.3309)
tensor(0.3270)
tensor(0.3233)
tensor(0.3196)
tensor(0.3160)
tensor(0.3125)
tensor(0.3091)
tensor(0.3057)
tensor(0.3024)
tensor(0.2992)
tensor(0.2961)
tensor(0.2931)
tensor(0.2901)
tensor(0.2872)
tensor(0.2843)
tensor(0.2815)
tensor(0.2

tensor(0.0555)
tensor(0.0555)
tensor(0.0554)
tensor(0.0553)
tensor(0.0552)
tensor(0.0552)
tensor(0.0551)
tensor(0.0550)
tensor(0.0549)
tensor(0.0549)
tensor(0.0548)
tensor(0.0547)
tensor(0.0546)
tensor(0.0546)
tensor(0.0545)
tensor(0.0544)
tensor(0.0543)
tensor(0.0543)
tensor(0.0542)
tensor(0.0541)
tensor(0.0540)
tensor(0.0540)
tensor(0.0539)
tensor(0.0538)
tensor(0.0537)
tensor(0.0537)
tensor(0.0536)
tensor(0.0535)
tensor(0.0535)
tensor(0.0534)
tensor(0.0533)
tensor(0.0532)
tensor(0.0532)
tensor(0.0531)
tensor(0.0530)
tensor(0.0530)
tensor(0.0529)
tensor(0.0528)
tensor(0.0528)
tensor(0.0527)
tensor(0.0526)
tensor(0.0526)
tensor(0.0525)
tensor(0.0524)
tensor(0.0523)
tensor(0.0523)
tensor(0.0522)
tensor(0.0521)
tensor(0.0521)
tensor(0.0520)
tensor(0.0519)
tensor(0.0519)
tensor(0.0518)
tensor(0.0517)
tensor(0.0517)
tensor(0.0516)
tensor(0.0515)
tensor(0.0515)
tensor(0.0514)
tensor(0.0513)
tensor(0.0513)
tensor(0.0512)
tensor(0.0511)
tensor(0.0511)
tensor(0.0510)
tensor(0.0510)
tensor(0.0

tensor(0.0302)
tensor(0.0302)
tensor(0.0302)
tensor(0.0301)
tensor(0.0301)
tensor(0.0301)
tensor(0.0301)
tensor(0.0300)
tensor(0.0300)
tensor(0.0300)
tensor(0.0300)
tensor(0.0300)
tensor(0.0299)
tensor(0.0299)
tensor(0.0299)
tensor(0.0299)
tensor(0.0299)
tensor(0.0298)
tensor(0.0298)
tensor(0.0298)
tensor(0.0298)
tensor(0.0298)
tensor(0.0297)
tensor(0.0297)
tensor(0.0297)
tensor(0.0297)
tensor(0.0297)
tensor(0.0296)
tensor(0.0296)
tensor(0.0296)
tensor(0.0296)
tensor(0.0296)
tensor(0.0295)
tensor(0.0295)
tensor(0.0295)
tensor(0.0295)
tensor(0.0295)
tensor(0.0294)
tensor(0.0294)
tensor(0.0294)
tensor(0.0294)
tensor(0.0294)
tensor(0.0293)
tensor(0.0293)
tensor(0.0293)
tensor(0.0293)
tensor(0.0293)
tensor(0.0292)
tensor(0.0292)
tensor(0.0292)
tensor(0.0292)
tensor(0.0292)
tensor(0.0291)
tensor(0.0291)
tensor(0.0291)
tensor(0.0291)
tensor(0.0291)
tensor(0.0290)
tensor(0.0290)
tensor(0.0290)
tensor(0.0290)
tensor(0.0290)
tensor(0.0289)
tensor(0.0289)
tensor(0.0289)
tensor(0.0289)
tensor(0.0

tensor(0.0210)
tensor(0.0210)
tensor(0.0210)
tensor(0.0210)
tensor(0.0210)
tensor(0.0210)
tensor(0.0210)
tensor(0.0209)
tensor(0.0209)
tensor(0.0209)
tensor(0.0209)
tensor(0.0209)
tensor(0.0209)
tensor(0.0209)
tensor(0.0209)
tensor(0.0209)
tensor(0.0209)
tensor(0.0209)
tensor(0.0208)
tensor(0.0208)
tensor(0.0208)
tensor(0.0208)
tensor(0.0208)
tensor(0.0208)
tensor(0.0208)
tensor(0.0208)
tensor(0.0208)
tensor(0.0208)
tensor(0.0207)
tensor(0.0207)
tensor(0.0207)
tensor(0.0207)
tensor(0.0207)
tensor(0.0207)
tensor(0.0207)
tensor(0.0207)
tensor(0.0207)
tensor(0.0207)
tensor(0.0206)
tensor(0.0206)
tensor(0.0206)
tensor(0.0206)
tensor(0.0206)
tensor(0.0206)
tensor(0.0206)
tensor(0.0206)
tensor(0.0206)
tensor(0.0206)
tensor(0.0206)
tensor(0.0205)
tensor(0.0205)
tensor(0.0205)
tensor(0.0205)
tensor(0.0205)
tensor(0.0205)
tensor(0.0205)
tensor(0.0205)
tensor(0.0205)
tensor(0.0205)
tensor(0.0204)
tensor(0.0204)
tensor(0.0204)
tensor(0.0204)
tensor(0.0204)
tensor(0.0204)
tensor(0.0204)
tensor(0.0

tensor(0.0167)
tensor(0.0167)
tensor(0.0167)
tensor(0.0167)
tensor(0.0167)
tensor(0.0167)
tensor(0.0167)
tensor(0.0167)
tensor(0.0167)
tensor(0.0167)
tensor(0.0167)
tensor(0.0167)
tensor(0.0167)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0166)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0165)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0164)
tensor(0.0163)
tensor(0.0163)
tensor(0.0163)
tensor(0.0

tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0137)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0136)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0135)
tensor(0.0

tensor(0.0116)
tensor(0.0116)
tensor(0.0116)
tensor(0.0116)
tensor(0.0116)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0115)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0114)
tensor(0.0

tensor(0.0102)
tensor(0.0102)
tensor(0.0102)
tensor(0.0102)
tensor(0.0102)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0101)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0100)
tensor(0.0

tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0090)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0089)
tensor(0.0

tensor(0.0082)
tensor(0.0082)
tensor(0.0082)
tensor(0.0082)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0081)
tensor(0.0

tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0074)
tensor(0.0

tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0068)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0067)
tensor(0.0

tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0062)
tensor(0.0061)
tensor(0.0061)
tensor(0.0061)
tensor(0.0061)
tensor(0.0061)
tensor(0.0061)
tensor(0.0061)
tensor(0.0061)
tensor(0.0

tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0057)
tensor(0.0

tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0054)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0053)
tensor(0.0

tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0050)
tensor(0.0

tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0048)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0047)
tensor(0.0

In [14]:
model(th.tensor([4.5]))

tensor([-4.2183], grad_fn=<AddBackward0>)

In [15]:
print(predict_tensor)

tensor([[  7.0825],
        [  8.8211],
        [  4.4747],
        [ -4.2182],
        [ -7.6954],
        [-12.9111]], grad_fn=<AddmmBackward>)


In [16]:
model(th.tensor([5.5]))

tensor([4.4747], grad_fn=<AddBackward0>)

In [17]:
model(th.tensor([4.5]))

tensor([-4.2183], grad_fn=<AddBackward0>)

In [18]:
model(th.tensor([-1.0]))

tensor([-52.0302], grad_fn=<AddBackward0>)

In [19]:
print(model.weight.data)

tensor([[8.6931]])


In [20]:
print(model.bias.data)

tensor([-43.3371])


In [21]:
x = -1

In [22]:
(10.0103*x)- 49.9336

-59.9439

# Example

In [1]:
import torch as th

In [2]:
input_tensor = th.tensor([[5.8],[6.0],[5.5],[4.5],[4.1],[3.5]],requires_grad=True)
target_tensor = th.tensor([[1.0],[1],[1],[0],[0],[0]],requires_grad=False)

In [3]:
from torch.optim import optimizer
from torch import optim
from torch import nn
import torch.nn.functional as F
import numpy
class Classifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(1,1)
    def forward(self,x):
        x = th.sigmoid(self.fc(x))
        return x

In [4]:
model = Classifier()
criterion = nn.BCEWithLogitsLoss()

optimizer = optim.SGD(model.parameters(), lr =0.4,momentum=0.8)

for i in range(10000):
    optimizer.zero_grad()
    predict_tensor = model(input_tensor)
    predict_tensor = th.log(predict_tensor)
    loss = criterion(predict_tensor,target_tensor)
    loss.backward()
    optimizer.step()
    print(loss.data)

tensor(0.6712)
tensor(0.6700)
tensor(0.6690)
tensor(0.6687)
tensor(0.6688)
tensor(0.6687)
tensor(0.6684)
tensor(0.6679)
tensor(0.6673)
tensor(0.6667)
tensor(0.6663)
tensor(0.6659)
tensor(0.6655)
tensor(0.6650)
tensor(0.6645)
tensor(0.6639)
tensor(0.6634)
tensor(0.6629)
tensor(0.6624)
tensor(0.6618)
tensor(0.6612)
tensor(0.6606)
tensor(0.6601)
tensor(0.6595)
tensor(0.6588)
tensor(0.6582)
tensor(0.6576)
tensor(0.6569)
tensor(0.6563)
tensor(0.6556)
tensor(0.6549)
tensor(0.6542)
tensor(0.6535)
tensor(0.6528)
tensor(0.6521)
tensor(0.6513)
tensor(0.6505)
tensor(0.6498)
tensor(0.6490)
tensor(0.6482)
tensor(0.6474)
tensor(0.6466)
tensor(0.6457)
tensor(0.6449)
tensor(0.6440)
tensor(0.6432)
tensor(0.6423)
tensor(0.6414)
tensor(0.6405)
tensor(0.6396)
tensor(0.6387)
tensor(0.6377)
tensor(0.6368)
tensor(0.6358)
tensor(0.6348)
tensor(0.6339)
tensor(0.6329)
tensor(0.6319)
tensor(0.6309)
tensor(0.6298)
tensor(0.6288)
tensor(0.6278)
tensor(0.6267)
tensor(0.6257)
tensor(0.6246)
tensor(0.6235)
tensor(0.6

tensor(0.4047)
tensor(0.4047)
tensor(0.4046)
tensor(0.4045)
tensor(0.4044)
tensor(0.4043)
tensor(0.4042)
tensor(0.4042)
tensor(0.4041)
tensor(0.4040)
tensor(0.4039)
tensor(0.4038)
tensor(0.4038)
tensor(0.4037)
tensor(0.4036)
tensor(0.4035)
tensor(0.4034)
tensor(0.4034)
tensor(0.4033)
tensor(0.4032)
tensor(0.4031)
tensor(0.4030)
tensor(0.4030)
tensor(0.4029)
tensor(0.4028)
tensor(0.4027)
tensor(0.4027)
tensor(0.4026)
tensor(0.4025)
tensor(0.4024)
tensor(0.4023)
tensor(0.4023)
tensor(0.4022)
tensor(0.4021)
tensor(0.4020)
tensor(0.4020)
tensor(0.4019)
tensor(0.4018)
tensor(0.4017)
tensor(0.4017)
tensor(0.4016)
tensor(0.4015)
tensor(0.4015)
tensor(0.4014)
tensor(0.4013)
tensor(0.4012)
tensor(0.4012)
tensor(0.4011)
tensor(0.4010)
tensor(0.4009)
tensor(0.4009)
tensor(0.4008)
tensor(0.4007)
tensor(0.4007)
tensor(0.4006)
tensor(0.4005)
tensor(0.4004)
tensor(0.4004)
tensor(0.4003)
tensor(0.4002)
tensor(0.4002)
tensor(0.4001)
tensor(0.4000)
tensor(0.3999)
tensor(0.3999)
tensor(0.3998)
tensor(0.3

tensor(0.3782)
tensor(0.3782)
tensor(0.3782)
tensor(0.3782)
tensor(0.3781)
tensor(0.3781)
tensor(0.3781)
tensor(0.3781)
tensor(0.3780)
tensor(0.3780)
tensor(0.3780)
tensor(0.3780)
tensor(0.3780)
tensor(0.3779)
tensor(0.3779)
tensor(0.3779)
tensor(0.3779)
tensor(0.3778)
tensor(0.3778)
tensor(0.3778)
tensor(0.3778)
tensor(0.3778)
tensor(0.3777)
tensor(0.3777)
tensor(0.3777)
tensor(0.3777)
tensor(0.3776)
tensor(0.3776)
tensor(0.3776)
tensor(0.3776)
tensor(0.3776)
tensor(0.3775)
tensor(0.3775)
tensor(0.3775)
tensor(0.3775)
tensor(0.3774)
tensor(0.3774)
tensor(0.3774)
tensor(0.3774)
tensor(0.3774)
tensor(0.3773)
tensor(0.3773)
tensor(0.3773)
tensor(0.3773)
tensor(0.3772)
tensor(0.3772)
tensor(0.3772)
tensor(0.3772)
tensor(0.3772)
tensor(0.3771)
tensor(0.3771)
tensor(0.3771)
tensor(0.3771)
tensor(0.3771)
tensor(0.3770)
tensor(0.3770)
tensor(0.3770)
tensor(0.3770)
tensor(0.3769)
tensor(0.3769)
tensor(0.3769)
tensor(0.3769)
tensor(0.3769)
tensor(0.3768)
tensor(0.3768)
tensor(0.3768)
tensor(0.3

tensor(0.3686)
tensor(0.3686)
tensor(0.3686)
tensor(0.3686)
tensor(0.3686)
tensor(0.3685)
tensor(0.3685)
tensor(0.3685)
tensor(0.3685)
tensor(0.3685)
tensor(0.3685)
tensor(0.3685)
tensor(0.3685)
tensor(0.3685)
tensor(0.3684)
tensor(0.3684)
tensor(0.3684)
tensor(0.3684)
tensor(0.3684)
tensor(0.3684)
tensor(0.3684)
tensor(0.3684)
tensor(0.3684)
tensor(0.3684)
tensor(0.3683)
tensor(0.3683)
tensor(0.3683)
tensor(0.3683)
tensor(0.3683)
tensor(0.3683)
tensor(0.3683)
tensor(0.3683)
tensor(0.3683)
tensor(0.3682)
tensor(0.3682)
tensor(0.3682)
tensor(0.3682)
tensor(0.3682)
tensor(0.3682)
tensor(0.3682)
tensor(0.3682)
tensor(0.3682)
tensor(0.3682)
tensor(0.3681)
tensor(0.3681)
tensor(0.3681)
tensor(0.3681)
tensor(0.3681)
tensor(0.3681)
tensor(0.3681)
tensor(0.3681)
tensor(0.3681)
tensor(0.3680)
tensor(0.3680)
tensor(0.3680)
tensor(0.3680)
tensor(0.3680)
tensor(0.3680)
tensor(0.3680)
tensor(0.3680)
tensor(0.3680)
tensor(0.3680)
tensor(0.3679)
tensor(0.3679)
tensor(0.3679)
tensor(0.3679)
tensor(0.3

tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3634)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3633)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3632)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3631)
tensor(0.3630)
tensor(0.3630)
tensor(0.3

tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3603)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3602)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3601)
tensor(0.3600)
tensor(0.3600)
tensor(0.3

tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3583)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3582)
tensor(0.3581)
tensor(0.3581)
tensor(0.3581)
tensor(0.3581)
tensor(0.3581)
tensor(0.3581)
tensor(0.3

tensor(0.3568)
tensor(0.3568)
tensor(0.3568)
tensor(0.3568)
tensor(0.3568)
tensor(0.3568)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3567)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3566)
tensor(0.3

tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3556)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3555)
tensor(0.3

tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3546)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3545)
tensor(0.3

tensor(0.3538)
tensor(0.3538)
tensor(0.3538)
tensor(0.3538)
tensor(0.3538)
tensor(0.3538)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3537)
tensor(0.3

tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3531)
tensor(0.3

tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3526)
tensor(0.3

tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3522)
tensor(0.3

tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3518)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3517)
tensor(0.3

tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3515)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3514)
tensor(0.3

tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)
tensor(0.3512)


In [5]:
model(th.tensor([4.5]))

tensor([0.0148], grad_fn=<SigmoidBackward>)

In [6]:
model(th.tensor([4.9]))

tensor([0.2693], grad_fn=<SigmoidBackward>)

In [7]:
model(th.tensor([5.0]))

tensor([0.4508], grad_fn=<SigmoidBackward>)

In [8]:
model(th.tensor([5.1]))

tensor([0.6464], grad_fn=<SigmoidBackward>)

# Proof of inverse of Sigmoid

In [29]:
x = -59.9439

In [30]:
sigmoid = 1/(1+numpy.exp(-x))

In [31]:
sigmoid

9.261791633098449e-27

In [32]:
sigmoid = th.sigmoid(th.tensor([x]))

In [33]:
th.log(sigmoid)

tensor([-59.9439])